"""create sensor_data table

Revision ID: 29afa55cfe04
Revises: 
Create Date: 2024-10-06 12:45:56.324143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29afa55cfe04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_sensor_id'), 'sensor_data', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_sensor_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
