"""Create file_uploads, sensor_data, and anomalies tables

Revision ID: 3f825bf2a01a
Revises: cd90bcc6c798
Create Date: 2024-10-07 12:07:56.539068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f825bf2a01a'
down_revision: Union[str, None] = 'cd90bcc6c798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_uploads', ['id'])
    op.add_column('sensor_data', sa.Column('file_upload_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sensor_data', 'file_uploads', ['file_upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.drop_column('sensor_data', 'file_upload_id')
    op.drop_constraint(None, 'file_uploads', type_='unique')
    # ### end Alembic commands ###
