"""AnamolyDetection model

Revision ID: cd90bcc6c798
Revises: 29afa55cfe04
Create Date: 2024-10-06 16:17:42.239188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd90bcc6c798'
down_revision: Union[str, None] = '29afa55cfe04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anomalies', ['id'])
    op.create_unique_constraint(None, 'sensor_data', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='unique')
    op.drop_constraint(None, 'anomalies', type_='unique')
    # ### end Alembic commands ###
